name: Auto Merge PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  statuses: write
  checks: read
  actions: read

jobs:
  check-and-merge:
    uses: aeassist-acr/workflows_center/.github/workflows/auto-merge-pr.yml@master
    secrets: inherit